build:
  image: elixir
  environment:
    - MIX_ENV=test
    - NODE_ENV=test
  commands:
    - yes | mix deps.get
    - yes | mix deps.compile
    - mix credo -a --strict
    - mix test --color
cache:
  mount:
    - _build
    - deps
